export const SET_GAME_RATING = 'SET_GAME_RATING';
export const SET_GAME_REVIEW = 'SET_GAME_REVIEW';
export const SET_GAME_SEARCH_INPUT = 'SET_GAME_SEARCH_INPUT';
export const SET_ADD_REVIEW_INPUT = 'SET_ADD_REVIEW_INPUT';
